import { z } from 'zod'
import { Identifier } from './sharedTypes'

export const KitSchema = z.object({
  url: z.string(),
  imageSrc: z.string(),
  recommendedEngines: z.string(),
  projectedMaxAltitude: z.string(),
  recoverySystem: z.string(),
  length: z.string(),
  diameter: z.string(),
  estimatedWeight: z.string(),
  estimatedAssemblyTime: z.string(),
  finMaterials: z.string(),
  decalType: z.string(),
  launchSystem: z.string(),
  launchRodSize: z.string(),
  instructions: z.string(),
  ageRecommendation: z.string(),
  mfgID: Identifier,
  name: z.string(),
  complexity: z.string(),
  height: z.string(),
  weight: z.string(),
  motorMount: z.string(),
  parachuteSize: z.string(),
  shockCordType: z.string(),
  shockCordMount: z.string(),
  finThickness: z.string(),
  ringThickness: z.string(),
  price: z.string(),
  currency: z.string(),
  sku: z.string(),
  stockStatus: z.string(),
  description: z.string().optional(),
  links: z.string(),
  parachute: z.string(),
  finArray: z.string(),
  uniqueID: Identifier,
  labels: z.array(z.string())
})
