<RockSimDocument>
  <FileVersion>4</FileVersion>
  <DesignInformation>
    <RocketDesign>
      <CalculateCD>1</CalculateCD>
      <ProCalculateCD>1</ProCalculateCD>
      <ProCalculateCN>1</ProCalculateCN>
      <FixedCd>0.75</FixedCd>
      <FixedCd2>0.8</FixedCd2>
      <FixedCd3>0.81</FixedCd3>
      <FixedCd2Alone>0.95</FixedCd2Alone>
      <FixedCd3Alone>0.95</FixedCd3Alone>
      <StageCount>1</StageCount>
      <Stage3Mass>0.</Stage3Mass>
      <Stage2Mass>0.</Stage2Mass>
      <Stage1Mass>0.</Stage1Mass>
      <Stage321CG>0.</Stage321CG>
      <Stage32CG>0.</Stage32CG>
      <Stage3CG>0.</Stage3CG>
      <Stage2CGAlone>0.</Stage2CGAlone>
      <Stage1CGAlone>0.</Stage1CGAlone>
      <CPCalcFlags>4</CPCalcFlags>
      <LaunchGuideLength>914.4</LaunchGuideLength>
      <UseKnownMass>0</UseKnownMass>
      <DefaultFinish>0</DefaultFinish>
      <FinishMedium>0</FinishMedium>
      <FinishCoatCount>1</FinishCoatCount>
      <GlueType>0</GlueType>
      <CPSimFlags>4</CPSimFlags>
      <LastSerialNumber>20</LastSerialNumber>
      <DisplayFlags>1</DisplayFlags>
      <MetricsFlags>0</MetricsFlags>
      <CameraState>CSV1|1|770.272,27.2203,-173.948|1571.34,2016.41,-803.6|-0.22233,0.374477,0.900187|1656.47,3196.76|30|2|2234.96|-34.7737|0|0|0|0</CameraState>
      <BarromanXN>0,1040.72,0,0</BarromanXN>
      <BarrowmanCNa>0,60.1234,0,0</BarrowmanCNa>
      <RockSimXN>0,1057.59,0,0</RockSimXN>
      <RockSimCNa>0,81.6613,0,0</RockSimCNa>
      <RockSimCNa90>0,0,0,0</RockSimCNa90>
      <RockSimXN90>0,0,0,0</RockSimXN90>
      <ViewType>2</ViewType>
      <ViewStageCount>1</ViewStageCount>
      <ViewTypeEdit>2</ViewTypeEdit>
      <ViewStageCountEdit>1</ViewStageCountEdit>
      <ZoomFactor>0.</ZoomFactor>
      <ZoomFactorEdit>0.</ZoomFactorEdit>
      <ScrollPosX>0</ScrollPosX>
      <ScrollPosY>0</ScrollPosY>
      <ScrollPosXEdit>0</ScrollPosXEdit>
      <ScrollPosYEdit>0</ScrollPosYEdit>
      <ThreeDFlags>0</ThreeDFlags>
      <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
      <UseModelSprite>0</UseModelSprite>
      <StaticMarginRef>1</StaticMarginRef>
      <UserRefDiameter>0.</UserRefDiameter>
      <SideMarkerHeight>9.99998</SideMarkerHeight>
      <SideDimensionHeight>9.99998</SideDimensionHeight>
      <BaseMarkerHeight>9.99998</BaseMarkerHeight>
      <BaseDimensionHeight>9.99998</BaseDimensionHeight>
      <ShowGlideCP>0</ShowGlideCP>
      <ShowGridTypeSide>0</ShowGridTypeSide>
      <ShowGridTypeBase>0</ShowGridTypeBase>
      <GridSpacing>10.</GridSpacing>
      <GridOpacity>0.15</GridOpacity>
      <GridColor>black</GridColor>
      <MaxDiaWithFins>141.351</MaxDiaWithFins>
      <MaxDiaWithoutFins>58.801</MaxDiaWithoutFins>
      <MaxLenWithFins>1379.68</MaxLenWithFins>
      <MaxLenWithoutFins>1379.68</MaxLenWithoutFins>
      <MinXExtent>0.</MinXExtent>
      <MaxXExtent>1379.68</MaxXExtent>
      <CalculatedMaxStageDia>0,58.801,0,0</CalculatedMaxStageDia>
      <CalculatedStageLen>0,1379.68,0,0</CalculatedStageLen>
      <Cd3>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cd3>
      <Cd32>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cd32>
      <Cd321>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cd321>
      <Cb3>
        <PolyData useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cb3>
      <Cb32>
        <PolyData useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cb32>
      <Cb321>
        <PolyData useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </Cb321>
      <CNa3>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CNa3>
      <CNa32>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CNa32>
      <CNa321>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CNa321>
      <CP3>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CP3>
      <CP32>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CP32>
      <CP321>
        <PolyData useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
          <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
          <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
          <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
          <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
        </PolyData>
      </CP321>
      <SimulationEventList>
        <SimulationEvent>
          <PartSerialNo>14</PartSerialNo>
          <Type>1</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
          <TestType>1,28,28</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>1</ProEvent>
        </SimulationEvent>
      </SimulationEventList>
      <Stage3Parts>
        <NoseCone>
          <PartMfg>Estes</PartMfg>
          <KnownMass>11.8</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Nose cone</Name>
          <KnownCG>72.9996</KnownCG>
          <UseKnownCG>1</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>33.541</CalcMass>
          <CalcCG>195.415</CalcCG>
          <WettedSurface>0.00631846</WettedSurface>
          <PaintedSurface>0.00631846</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <PartDesc>BBXII Blow-Molded Nose Cone</PartDesc>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.49,0.5,0.5)|scale=(1,1,1)|repeat=(0)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(0)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(200,200,200)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>1</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>2.</BarrowmanCNa>
          <BarrowmanXN>0.0455794</BarrowmanXN>
          <RockSimCNa>2.</RockSimCNa>
          <RockSimXN>0.0455794</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>0.</Station>
          <Len>98.425</Len>
          <BaseDia>30.226</BaseDia>
          <FinishCode>0</FinishCode>
          <ShapeCode>1</ShapeCode>
          <ConstructionType>1</ConstructionType>
          <ShoulderLen>41.1988</ShoulderLen>
          <WallThickness>1.0668</WallThickness>
          <ShapeParameter>0.</ShapeParameter>
          <ShoulderOD>28.7528</ShoulderOD>
          <BaseExtensionLen>215.9</BaseExtensionLen>
          <CoreDia>0.</CoreDia>
          <CoreLen>0.</CoreLen>
          <AttachedParts>
            <MassObject>
              <PartMfg>Estes</PartMfg>
              <KnownMass>30.</KnownMass>
              <Density>0.</Density>
              <Material>Aluminum</Material>
              <Name>Clay Nose Weight</Name>
              <KnownCG>25.4</KnownCG>
              <UseKnownCG>1</UseKnownCG>
              <Xb>25.4</Xb>
              <CalcMass>0.</CalcMass>
              <CalcCG>0.</CalcCG>
              <WettedSurface>0.</WettedSurface>
              <PaintedSurface>0.</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>blue</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>20</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>0</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>0.</BarrowmanCNa>
              <BarrowmanXN>0.</BarrowmanXN>
              <RockSimCNa>0.</RockSimCNa>
              <RockSimXN>0.</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>25.4</Station>
              <TypeCode>0</TypeCode>
              <Len>0.</Len>
              <AttachedParts>
              </AttachedParts>
            </MassObject>
          </AttachedParts>
        </NoseCone>
        <BodyTube>
          <PartMfg>Apogee</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1121.29</Density>
          <Material>Paper</Material>
          <Name>Upper Stage Body Tube</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>23.733</CalcMass>
          <CalcCG>203.2</CalcCG>
          <WettedSurface>0.0385908</WettedSurface>
          <PaintedSurface>0.0385908</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <PartNo>10110</PartNo>
          <PartDesc><![CDATA[29mm x 13" Motor Mount]]></PartDesc>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(0)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(0,0,0)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>2</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.</BarrowmanCNa>
          <BarrowmanXN>0.</BarrowmanXN>
          <RockSimCNa>0.</RockSimCNa>
          <RockSimXN>0.</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>314.325</Station>
          <OD>30.226</OD>
          <ID>29.1084</ID>
          <Len>406.4</Len>
          <FinishCode>0</FinishCode>
          <IsMotorMount>0</IsMotorMount>
          <MotorDia>0.</MotorDia>
          <EngineOverhang>0.5</EngineOverhang>
          <FrontExtension>0.</FrontExtension>
          <RearExtension>0.</RearExtension>
          <IsInsideTube>0</IsInsideTube>
          <isStrapOnTube>0</isStrapOnTube>
          <AttachedParts>
          </AttachedParts>
        </BodyTube>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Upper Stage Transition A</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>8.524</CalcMass>
          <CalcCG>35.8092</CalcCG>
          <WettedSurface>0.0044227</WettedSurface>
          <PaintedSurface>0.0044227</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(128,128,114)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>4</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.0337547</BarrowmanCNa>
          <BarrowmanXN>0.743948</BarrowmanXN>
          <RockSimCNa>0.0337547</RockSimCNa>
          <RockSimXN>0.743948</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>720.725</Station>
          <FrontDia>30.226</FrontDia>
          <RearDia>30.48</RearDia>
          <Len>46.3804</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>30.8102</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.0668</WallThickness>
          <FrontShoulderDia>28.8544</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>5565.65</EquivNoseLen>
          <EquivNoseOffset>5519.27</EquivNoseOffset>
          <AttachedParts>
            <CustomFinSet>
              <PartMfg>Custom</PartMfg>
              <KnownMass>15.3</KnownMass>
              <Density>1049.21</Density>
              <Material>Polystyrene PS</Material>
              <Name>Fin set</Name>
              <KnownCG>60.96</KnownCG>
              <UseKnownCG>1</UseKnownCG>
              <Xb>0.</Xb>
              <CalcMass>24.4924</CalcMass>
              <CalcCG>62.5465</CalcCG>
              <WettedSurface>0.00489894</WettedSurface>
              <PaintedSurface>0.0195958</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>rgb(0,0,0)</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>19</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>13.4232</BarrowmanCNa>
              <BarrowmanXN>0.735613</BarrowmanXN>
              <RockSimCNa>17.7685</RockSimCNa>
              <RockSimXN>0.737384</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>688.619</Station>
              <FinCount>4</FinCount>
              <RootChord>78.49</RootChord>
              <TipChord>47.13</TipChord>
              <SemiSpan>38.1</SemiSpan>
              <MidChordLen>64.3592</MidChordLen>
              <SweepDistance>67.55</SweepDistance>
              <Thickness>2.38252</Thickness>
              <ShapeCode>2</ShapeCode>
              <FinishCode>0</FinishCode>
              <TipShapeCode>2</TipShapeCode>
              <TabLength>0.</TabLength>
              <TabDepth>0.</TabDepth>
              <TabOffset>0.</TabOffset>
              <SweepMode>1</SweepMode>
              <SweepAngle>0.</SweepAngle>
              <RockSimXNPerFin>0.</RockSimXNPerFin>
              <RockSimRadialXNPerFin>32.5778</RockSimRadialXNPerFin>
              <RockSimCNaPerFin>8.88423</RockSimCNaPerFin>
              <TaperRatio>0.600459</TaperRatio>
              <CantAngle>0.</CantAngle>
              <CantPivotPoint>0.</CantPivotPoint>
              <AverageChord>64.4</AverageChord>
              <EffectiveTipChord>47.1315</EffectiveTipChord>
              <PointList>78.486,0|91.3384,7.5692|108.737,38.1|65.3288,38.1|0,0|</PointList>
              <AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
              <GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
              <UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
              <GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
              <SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
              <AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
              <GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
              <UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
              <GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
              <SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
              <AttachedParts>
              </AttachedParts>
            </CustomFinSet>
          </AttachedParts>
        </Transition>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Upper Stage Transition B</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>3.442</CalcMass>
          <CalcCG>14.445</CalcCG>
          <WettedSurface>0.00316711</WettedSurface>
          <PaintedSurface>0.00316711</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(200,200,200)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>5</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>1.76025</BarrowmanCNa>
          <BarrowmanXN>0.781528</BarrowmanXN>
          <RockSimCNa>1.76025</RockSimCNa>
          <RockSimXN>0.781528</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>767.105</Station>
          <FrontDia>30.48</FrontDia>
          <RearDia>41.6306</RearDia>
          <Len>27.432</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.0668</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>102.415</EquivNoseLen>
          <EquivNoseOffset>74.9826</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Upper Stage Transition C</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>8.815</CalcMass>
          <CalcCG>11.4214</CalcCG>
          <WettedSurface>0.00280173</WettedSurface>
          <PaintedSurface>0.00280173</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(200,200,200)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>6</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.00499323</BarrowmanCNa>
          <BarrowmanXN>0.805257</BarrowmanXN>
          <RockSimCNa>0.00499323</RockSimCNa>
          <RockSimXN>0.805257</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>794.537</Station>
          <FrontDia>41.6306</FrontDia>
          <RearDia>41.656</RearDia>
          <Len>21.4376</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>31.115</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.0668</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>40.5003</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>32606.6</EquivNoseLen>
          <EquivNoseOffset>32585.2</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
        <BodyTube>
          <PartMfg>Apogee</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1121.29</Density>
          <Material>Paper</Material>
          <Name>Second Stage Body Tube</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>12.585</CalcMass>
          <CalcCG>117.475</CalcCG>
          <WettedSurface>0.030747</WettedSurface>
          <PaintedSurface>0.030747</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <PartNo>10141</PartNo>
          <PartDesc><![CDATA[41.6mm x 18" Body Tube]]></PartDesc>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(0)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(255,85,0)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>7</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.</BarrowmanCNa>
          <BarrowmanXN>0.</BarrowmanXN>
          <RockSimCNa>0.</RockSimCNa>
          <RockSimXN>0.</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>815.975</Station>
          <OD>41.656</OD>
          <ID>40.9194</ID>
          <Len>234.95</Len>
          <FinishCode>0</FinishCode>
          <IsMotorMount>0</IsMotorMount>
          <MotorDia>0.</MotorDia>
          <EngineOverhang>0.5</EngineOverhang>
          <FrontExtension>0.</FrontExtension>
          <RearExtension>0.</RearExtension>
          <IsInsideTube>0</IsInsideTube>
          <isStrapOnTube>0</isStrapOnTube>
          <AttachedParts>
            <Parachute>
              <PartMfg>Estes</PartMfg>
              <KnownMass>25.3</KnownMass>
              <Density>0.0054</Density>
              <Material>Rip stop nylon</Material>
              <Name>Parachute</Name>
              <KnownCG>0.</KnownCG>
              <UseKnownCG>1</UseKnownCG>
              <Xb>41.275</Xb>
              <CalcMass>15.0104</CalcMass>
              <CalcCG>50.8</CalcCG>
              <WettedSurface>0.</WettedSurface>
              <PaintedSurface>0.</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>1</DensityType>
              <PartNo>82426-30</PartNo>
              <PartDesc>24 in. nylon</PartDesc>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>blue</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>14</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>0</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>0.</BarrowmanCNa>
              <BarrowmanXN>0.</BarrowmanXN>
              <RockSimCNa>0.</RockSimCNa>
              <RockSimXN>0.</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>857.25</Station>
              <Dia>609.6</Dia>
              <SpillHoleDia>0.</SpillHoleDia>
              <SideCount>6</SideCount>
              <ShroudLineCount>8</ShroudLineCount>
              <Thickness>0.254</Thickness>
              <ShroudLineLen>749.3</ShroudLineLen>
              <ChuteCount>1</ChuteCount>
              <ShroudLineMassPerMM>0.00032972</ShroudLineMassPerMM>
              <ShroudLineMaterial>Carpet String (Apogee 29500)</ShroudLineMaterial>
              <DragCoefficient>0.75</DragCoefficient>
              <AttachedParts>
              </AttachedParts>
            </Parachute>
          </AttachedParts>
        </BodyTube>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Second Stage Boattail</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>11.199</CalcMass>
          <CalcCG>33.3736</CalcCG>
          <WettedSurface>0.00740684</WettedSurface>
          <PaintedSurface>0.00740684</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(255,85,0)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>8</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>-0.692515</BarrowmanCNa>
          <BarrowmanXN>1.08013</BarrowmanXN>
          <RockSimCNa>-0.692515</RockSimCNa>
          <RockSimXN>1.08013</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1050.92</Station>
          <FrontDia>41.656</FrontDia>
          <RearDia>37.6682</RearDia>
          <Len>59.4106</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>16.8402</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.016</WallThickness>
          <FrontShoulderDia>39.6748</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>620.562</EquivNoseLen>
          <EquivNoseOffset>561.152</EquivNoseOffset>
          <AttachedParts>
            <CustomFinSet>
              <PartMfg>Custom</PartMfg>
              <KnownMass>12.4</KnownMass>
              <Density>128.148</Density>
              <Material>Balsa</Material>
              <Name>Second Stage Fin Set</Name>
              <KnownCG>32.9692</KnownCG>
              <UseKnownCG>1</UseKnownCG>
              <Xb>0.</Xb>
              <CalcMass>5.80369</CalcMass>
              <CalcCG>32.5322</CalcCG>
              <WettedSurface>0.00449033</WettedSurface>
              <PaintedSurface>0.0179613</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>rgb(255,0,0)</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>18</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>19.6489</BarrowmanCNa>
              <BarrowmanXN>1.07462</BarrowmanXN>
              <RockSimCNa>28.2493</RockSimCNa>
              <RockSimXN>1.07431</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>1053.78</Station>
              <FinCount>4</FinCount>
              <RootChord>56.55</RootChord>
              <TipChord>38.65</TipChord>
              <SemiSpan>45.21</SemiSpan>
              <MidChordLen>46.2642</MidChordLen>
              <SweepDistance>18.77</SweepDistance>
              <Thickness>4.7625</Thickness>
              <ShapeCode>2</ShapeCode>
              <FinishCode>0</FinishCode>
              <TipShapeCode>2</TipShapeCode>
              <TabLength>28.6004</TabLength>
              <TabDepth>5.61848</TabDepth>
              <TabOffset>15.367</TabOffset>
              <SweepMode>1</SweepMode>
              <SweepAngle>0.</SweepAngle>
              <RockSimXNPerFin>0.</RockSimXNPerFin>
              <RockSimRadialXNPerFin>42.76</RockSimRadialXNPerFin>
              <RockSimCNaPerFin>14.1247</RockSimCNaPerFin>
              <TaperRatio>0.683466</TaperRatio>
              <CantAngle>0.</CantAngle>
              <CantPivotPoint>0.</CantPivotPoint>
              <AverageChord>48.59</AverageChord>
              <EffectiveTipChord>38.6463</EffectiveTipChord>
              <PointList>56.5531,0|64.7192,4.5212|48.2981,45.212|16.764,45.212|0,0|</PointList>
              <AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
              <GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
              <UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
              <GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
              <SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
              <AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
              <GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
              <UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
              <GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
              <SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
              <AttachedParts>
              </AttachedParts>
            </CustomFinSet>
          </AttachedParts>
        </Transition>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Second Stage Transition A</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>4.696</CalcMass>
          <CalcCG>15.3178</CalcCG>
          <WettedSurface>0.00450185</WettedSurface>
          <PaintedSurface>0.00450185</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(200,200,200)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>9</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>4.05626</BarrowmanCNa>
          <BarrowmanXN>1.12563</BarrowmanXN>
          <RockSimCNa>4.05626</RockSimCNa>
          <RockSimXN>1.12563</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1110.34</Station>
          <FrontDia>37.6682</FrontDia>
          <RearDia>57.2008</RearDia>
          <Len>28.6258</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.016</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>83.8367</EquivNoseLen>
          <EquivNoseOffset>55.2109</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>Second Stage Transition B</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>9.748</CalcMass>
          <CalcCG>7.99248</CalcCG>
          <WettedSurface>0.00249192</WettedSurface>
          <PaintedSurface>0.00249192</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(59,0,0)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>10</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>-0.28364</BarrowmanCNa>
          <BarrowmanXN>1.14594</BarrowmanXN>
          <RockSimCNa>-0.28364</RockSimCNa>
          <RockSimXN>1.14594</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1138.96</Station>
          <FrontDia>57.2008</FrontDia>
          <RearDia>56.0578</RearDia>
          <Len>13.9954</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>25.4</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.016</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>55.0672</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>699.77</EquivNoseLen>
          <EquivNoseOffset>685.775</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
        <BodyTube>
          <PartMfg>Apogee</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1121.29</Density>
          <Material>Paper</Material>
          <Name>First Stage Body Tube</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>10.996</CalcMass>
          <CalcCG>77.7875</CalcCG>
          <WettedSurface>0.0274605</WettedSurface>
          <PaintedSurface>0.0274605</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <PartNo>10164</PartNo>
          <PartDesc><![CDATA[56mm x 18" Body Tube]]></PartDesc>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(0)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(255,255,255)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>11</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.</BarrowmanCNa>
          <BarrowmanXN>0.</BarrowmanXN>
          <RockSimCNa>0.</RockSimCNa>
          <RockSimXN>0.</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1152.96</Station>
          <OD>56.1848</OD>
          <ID>55.466</ID>
          <Len>155.575</Len>
          <FinishCode>0</FinishCode>
          <IsMotorMount>0</IsMotorMount>
          <MotorDia>0.</MotorDia>
          <EngineOverhang>0.5</EngineOverhang>
          <FrontExtension>0.</FrontExtension>
          <RearExtension>0.</RearExtension>
          <IsInsideTube>0</IsInsideTube>
          <isStrapOnTube>0</isStrapOnTube>
          <AttachedParts>
          </AttachedParts>
        </BodyTube>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>First Stage Boattail A</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>10.1124</CalcMass>
          <CalcCG>15.7506</CalcCG>
          <WettedSurface>0.00285201</WettedSurface>
          <PaintedSurface>0.00285201</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(255,255,255)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>12</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>0.689675</BarrowmanCNa>
          <BarrowmanXN>1.31647</BarrowmanXN>
          <RockSimCNa>0.689675</RockSimCNa>
          <RockSimXN>1.31647</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1308.53</Station>
          <FrontDia>56.0578</FrontDia>
          <RearDia>58.801</RearDia>
          <Len>15.748</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>25.4</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.016</WallThickness>
          <FrontShoulderDia>54.991</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>337.598</EquivNoseLen>
          <EquivNoseOffset>321.85</EquivNoseOffset>
          <AttachedParts>
          </AttachedParts>
        </Transition>
        <Transition>
          <PartMfg>Custom</PartMfg>
          <KnownMass>0.</KnownMass>
          <Density>1049.21</Density>
          <Material>Polystyrene PS</Material>
          <Name>First Stage Boattail B</Name>
          <KnownCG>0.</KnownCG>
          <UseKnownCG>0</UseKnownCG>
          <Xb>0.</Xb>
          <CalcMass>10.649</CalcMass>
          <CalcCG>27.6545</CalcCG>
          <WettedSurface>0.0101563</WettedSurface>
          <PaintedSurface>0.0101563</PaintedSurface>
          <GlueJointLength>0.</GlueJointLength>
          <DensityType>0</DensityType>
          <RadialLoc>0.</RadialLoc>
          <RadialAngle>0.</RadialAngle>
          <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
          <Opacity>1.</Opacity>
          <Specular>0.</Specular>
          <SpecularPower>1.</SpecularPower>
          <Ambient>0.</Ambient>
          <Diffuse>1.</Diffuse>
          <AbientColor>blue</AbientColor>
          <DiffuseColor>rgb(255,255,255)</DiffuseColor>
          <SpecularColor>white</SpecularColor>
          <UseSingleColor>1</UseSingleColor>
          <SerialNo>13</SerialNo>
          <DisplayFlags>0</DisplayFlags>
          <MetricsFlags>0</MetricsFlags>
          <LocationMode>0</LocationMode>
          <Color>blue</Color>
          <BarrowmanCNa>-0.227626</BarrowmanCNa>
          <BarrowmanXN>1.35191</BarrowmanXN>
          <RockSimCNa>-0.227626</RockSimCNa>
          <RockSimXN>1.35191</RockSimXN>
          <SimpleColorModel>1</SimpleColorModel>
          <ProduceTemplate>0</ProduceTemplate>
          <TemplateUnits>8</TemplateUnits>
          <Removed>0</Removed>
          <Station>1324.28</Station>
          <FrontDia>58.801</FrontDia>
          <RearDia>57.912</RearDia>
          <Len>55.3974</Len>
          <FinishCode>0</FinishCode>
          <FrontShoulderLen>0.</FrontShoulderLen>
          <RearShoulderLen>0.</RearShoulderLen>
          <ConstructionType>1</ConstructionType>
          <WallThickness>1.016</WallThickness>
          <FrontShoulderDia>0.</FrontShoulderDia>
          <RearShoulderDia>0.</RearShoulderDia>
          <CoreDia>0.</CoreDia>
          <ShapeCode>0</ShapeCode>
          <ShapeParameter>0.</ShapeParameter>
          <EquivNoseLen>3656.23</EquivNoseLen>
          <EquivNoseOffset>3600.83</EquivNoseOffset>
          <AttachedParts>
            <BodyTube>
              <PartMfg>Apogee</PartMfg>
              <KnownMass>0.</KnownMass>
              <Density>1121.29</Density>
              <Material>Paper</Material>
              <Name>MMT</Name>
              <KnownCG>0.</KnownCG>
              <UseKnownCG>0</UseKnownCG>
              <Xb>0.</Xb>
              <CalcMass>21.2294</CalcMass>
              <CalcCG>177.8</CalcCG>
              <WettedSurface>0.033767</WettedSurface>
              <PaintedSurface>0.033767</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <PartNo>10110</PartNo>
              <PartDesc><![CDATA[29mm x 13" Motor Mount]]></PartDesc>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>rgb(255,255,0)</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>15</SerialNo>
              <DisplayFlags>1</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>0.</BarrowmanCNa>
              <BarrowmanXN>0.</BarrowmanXN>
              <RockSimCNa>0.</RockSimCNa>
              <RockSimXN>0.</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>1024.08</Station>
              <OD>30.226</OD>
              <ID>29.083</ID>
              <Len>355.6</Len>
              <FinishCode>0</FinishCode>
              <IsMotorMount>1</IsMotorMount>
              <MotorDia>29.</MotorDia>
              <EngineOverhang>6.35</EngineOverhang>
              <FrontExtension>0.</FrontExtension>
              <RearExtension>0.</RearExtension>
              <IsInsideTube>1</IsInsideTube>
              <isStrapOnTube>0</isStrapOnTube>
              <AttachedParts>
                <MassObject>
                  <PartMfg>Estes</PartMfg>
                  <KnownMass>13.3</KnownMass>
                  <Density>0.00402</Density>
                  <Material>Aluminum</Material>
                  <Name>29mm Estes Retainer</Name>
                  <KnownCG>6.35</KnownCG>
                  <UseKnownCG>1</UseKnownCG>
                  <Xb>6.35</Xb>
                  <CalcMass>0.</CalcMass>
                  <CalcCG>0.</CalcCG>
                  <WettedSurface>0.</WettedSurface>
                  <PaintedSurface>0.</PaintedSurface>
                  <GlueJointLength>0.</GlueJointLength>
                  <DensityType>2</DensityType>
                  <PartNo>24020</PartNo>
                  <PartDesc>29mm Engine Retainer</PartDesc>
                  <RadialLoc>0.</RadialLoc>
                  <RadialAngle>0.</RadialAngle>
                  <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
                  <Opacity>1.</Opacity>
                  <Specular>0.</Specular>
                  <SpecularPower>1.</SpecularPower>
                  <Ambient>0.</Ambient>
                  <Diffuse>1.</Diffuse>
                  <AbientColor>blue</AbientColor>
                  <DiffuseColor>blue</DiffuseColor>
                  <SpecularColor>white</SpecularColor>
                  <UseSingleColor>1</UseSingleColor>
                  <SerialNo>16</SerialNo>
                  <DisplayFlags>0</DisplayFlags>
                  <MetricsFlags>0</MetricsFlags>
                  <LocationMode>2</LocationMode>
                  <Color>blue</Color>
                  <BarrowmanCNa>0.</BarrowmanCNa>
                  <BarrowmanXN>0.</BarrowmanXN>
                  <RockSimCNa>0.</RockSimCNa>
                  <RockSimXN>0.</RockSimXN>
                  <SimpleColorModel>1</SimpleColorModel>
                  <ProduceTemplate>0</ProduceTemplate>
                  <TemplateUnits>8</TemplateUnits>
                  <Removed>0</Removed>
                  <Station>1373.33</Station>
                  <TypeCode>0</TypeCode>
                  <Len>0.</Len>
                  <AttachedParts>
                  </AttachedParts>
                </MassObject>
              </AttachedParts>
            </BodyTube>
            <FinSet>
              <PartMfg>Custom</PartMfg>
              <KnownMass>19.5</KnownMass>
              <Density>128.148</Density>
              <Material>Balsa</Material>
              <Name>First Stage Fin Set</Name>
              <KnownCG>41.91</KnownCG>
              <UseKnownCG>1</UseKnownCG>
              <Xb>0.</Xb>
              <CalcMass>11.9486</CalcMass>
              <CalcCG>48.5007</CalcCG>
              <WettedSurface>0.00654359</WettedSurface>
              <PaintedSurface>0.0261744</PaintedSurface>
              <GlueJointLength>0.</GlueJointLength>
              <DensityType>0</DensityType>
              <RadialLoc>0.</RadialLoc>
              <RadialAngle>0.</RadialAngle>
              <Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr=(0)|flips=(0)|flipt=(0)|preventseam=(1)|rotate=(0)</Texture>
              <Opacity>1.</Opacity>
              <Specular>0.</Specular>
              <SpecularPower>1.</SpecularPower>
              <Ambient>0.</Ambient>
              <Diffuse>1.</Diffuse>
              <AbientColor>blue</AbientColor>
              <DiffuseColor>rgb(255,255,0)</DiffuseColor>
              <SpecularColor>white</SpecularColor>
              <UseSingleColor>1</UseSingleColor>
              <SerialNo>17</SerialNo>
              <DisplayFlags>0</DisplayFlags>
              <MetricsFlags>0</MetricsFlags>
              <LocationMode>2</LocationMode>
              <Color>blue</Color>
              <BarrowmanCNa>19.7102</BarrowmanCNa>
              <BarrowmanXN>1.31876</BarrowmanXN>
              <RockSimCNa>28.3024</RockSimCNa>
              <RockSimXN>1.31876</RockSimXN>
              <SimpleColorModel>1</SimpleColorModel>
              <ProduceTemplate>0</ProduceTemplate>
              <TemplateUnits>8</TemplateUnits>
              <Removed>0</Removed>
              <Station>1290.78</Station>
              <FinCount>4</FinCount>
              <RootChord>88.9</RootChord>
              <TipChord>73.025</TipChord>
              <SemiSpan>41.275</SemiSpan>
              <MidChordLen>42.0313</MidChordLen>
              <SweepDistance>15.875</SweepDistance>
              <Thickness>6.35</Thickness>
              <ShapeCode>0</ShapeCode>
              <FinishCode>0</FinishCode>
              <TipShapeCode>2</TipShapeCode>
              <TabLength>28.2194</TabLength>
              <TabDepth>12.9794</TabDepth>
              <TabOffset>37.338</TabOffset>
              <SweepMode>1</SweepMode>
              <SweepAngle>0.369992</SweepAngle>
              <RockSimXNPerFin>0.</RockSimXNPerFin>
              <RockSimRadialXNPerFin>48.0756</RockSimRadialXNPerFin>
              <RockSimCNaPerFin>14.1512</RockSimCNaPerFin>
              <TaperRatio>0.821429</TaperRatio>
              <CantAngle>0.</CantAngle>
              <CantPivotPoint>0.</CantPivotPoint>
              <AttachedParts>
              </AttachedParts>
            </FinSet>
          </AttachedParts>
        </Transition>
      </Stage3Parts>
      <Stage2Parts>
      </Stage2Parts>
      <Stage1Parts>
      </Stage1Parts>
      <SideViewDims>
      </SideViewDims>
      <BaseViewDims>
      </BaseViewDims>
      <VertViewDims>
      </VertViewDims>
    </RocketDesign>
  </DesignInformation>
  <SimulationResultsList>
    <SimulationResults>
      <MaxAltitude>239.771</MaxAltitude>
      <MaxVelocity>75.2234</MaxVelocity>
      <MaxAcceleration>67.7385</MaxAcceleration>
      <TimeToApogee>6.6975</TimeToApogee>
      <OptimalDelay>4.60625</OptimalDelay>
      <MultiDelayCount>1</MultiDelayCount>
      <VelocityAtDeplyment>17.6256</VelocityAtDeplyment>
      <AltitudeAtDeployment>236.96</AltitudeAtDeployment>
      <DelayTime>4</DelayTime>
      <EjectTime>6.09125</EjectTime>
      <FinalState>0</FinalState>
      <TimeToBurnout>2.09125</TimeToBurnout>
      <TimeToLanding>52.1087</TimeToLanding>
      <TimeToEject>6.09125</TimeToEject>
      <MinLaunchGuideLen>1.5999</MinLaunchGuideLen>
      <MaxVertVelocity>73.948</MaxVertVelocity>
      <MaxHorzVelocity>4.02811</MaxHorzVelocity>
      <MaxVertAcceleration>67.7385</MaxVertAcceleration>
      <MaxHorzAcceleration>54.7884</MaxHorzAcceleration>
      <MaxRange>137.18</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartRollRate>0.</LaunchStartRollRate>
      <LaunchGuideType>0</LaunchGuideType>
      <LaunchGuideLen>2438.4</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
      <LaunchGuideElevation>0.</LaunchGuideElevation>
      <LaunchBarometer>750.062</LaunchBarometer>
      <LaunchLatitude>37.</LaunchLatitude>
      <LaunchLongitude>0.</LaunchLongitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>213.36</LaunchAltitude>
      <LaunchLandingAltitude>213.36</LaunchLandingAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>4</LaunchWindPreset>
      <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>6.6609</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>99</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchWindTableSize>0</LaunchWindTableSize>
      <LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
      <LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
      <LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <CNaMultiplier>1.</CNaMultiplier>
      <CdMultiplier>1.</CdMultiplier>
      <CPOffset>0.</CPOffset>
      <SaveSimAsText>0</SaveSimAsText>
      <OutputAtMaxRes>0</OutputAtMaxRes>
      <MaxSimTim>3600.</MaxSimTim>
      <MassUncertainty>0.</MassUncertainty>
      <MOIUncertainty>0.</MOIUncertainty>
      <CGUncertainty>0.</CGUncertainty>
      <CdUncertainty>0.</CdUncertainty>
      <CnaUncertainty>0.</CnaUncertainty>
      <CPUncertainty>0.</CPUncertainty>
      <FinCantUncertainty>0.</FinCantUncertainty>
      <TotImpulseUncertainty>0.</TotImpulseUncertainty>
      <PropellantUncertainty>0.</PropellantUncertainty>
      <ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
      <WindDirectionUncertainty>0.</WindDirectionUncertainty>
      <WindVelocityUncertainty>0.</WindVelocityUncertainty>
      <LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
      <LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
      <IgnitionUncertainty>0.</IgnitionUncertainty>
      <CATOUncertainty>0.</CATOUncertainty>
      <DeploymentUncertainty>0.</DeploymentUncertainty>
      <RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
      <SimulationName>[E16-4] </SimulationName>
      <VelocityAtLaunchGuideEnd>16.8929</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.60875</TimeToFreeFlight>
      <TimeToMaxVelocity>2.05625</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.52125</TimeToMaxAcceleration>
      <Nsims>0</Nsims>
      <CalcResolution>1</CalcResolution>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>4</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
      <ExecutionTime>0.319</ExecutionTime>
      <RangeAtLanding>137.18</RangeAtLanding>
      <DirectionAtLanding>0.</DirectionAtLanding>
      <VelocityAtLanding>6.65192</VelocityAtLanding>
      <XVelcoityAtLanding>4.02811</XVelcoityAtLanding>
      <YVelocityAtLanding>-5.29362</YVelocityAtLanding>
      <ZVelocityAtLanding>0.</ZVelocityAtLanding>
      <StageSeparationTime>0,0,6.09125,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
      <TimeToDeployment>0,0,6.09125,0,0</TimeToDeployment>
      <DeploymentType>32,32,80,32,32</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>345.329</Mass0>
      <CG0>976.485</CG0>
      <LaterialMOI0>463340.</LaterialMOI0>
      <RadialMOI0>0.000141695</RadialMOI0>
      <CP0>1057.6</CP0>
      <CNA0>81.6615</CNA0>
      <SM0>1.37947</SM0>
      <GUID>{54f03a7c-c628-4656-8d9d-c0485545c02d}</GUID>
      <WeatherCocking>1</WeatherCocking>
      <RecommendedDelay>4.</RecommendedDelay>
      <RecommendedMotor>0</RecommendedMotor>
      <RecommendedMotorChecked>0</RecommendedMotorChecked>
      <TrueIndex>0</TrueIndex>
      <NinetyDegDanger>1</NinetyDegDanger>
      <VelocityGuideSafe>1</VelocityGuideSafe>
      <StaticMarginSafe>0</StaticMarginSafe>
      <VelocityDeploySafe>1</VelocityDeploySafe>
      <Booster1Staging>
        <SimulationEvent>
          <PartSerialNo>0</PartSerialNo>
          <Type>0</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
          <TestType>0,0,0</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>0</ProEvent>
        </SimulationEvent>
      </Booster1Staging>
      <Booster2Staging>
        <SimulationEvent>
          <PartSerialNo>0</PartSerialNo>
          <Type>0</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
          <TestType>0,0,0</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>0</ProEvent>
        </SimulationEvent>
      </Booster2Staging>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>14</PartSerialNo>
          <Type>1</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>236.96</DeployedAt_Altitude>
          <DeployedAt_Velocity>17.6256</DeployedAt_Velocity>
          <DeployedAt_Range>-43.2866</DeployedAt_Range>
          <DeployedAt_Time>6.09125</DeployedAt_Time>
          <DeviceID>128</DeviceID>
          <TestType>1,28,28</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>1</ProEvent>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>E16</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Estes Industries, Inc.</EngineMfg>
          <EngineOverhang>6.35</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>15</MountSerialNo>
          <EjectionDelay>4.</EjectionDelay>
          <RotateXaboutY>0.</RotateXaboutY>
          <RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
        </EngineSet>
      </Stage3Engines>
      <DropItems>
      </DropItems>
    </SimulationResults>
    <SimulationResults>
      <MaxAltitude>361.922</MaxAltitude>
      <MaxVelocity>89.1234</MaxVelocity>
      <MaxAcceleration>64.0525</MaxAcceleration>
      <TimeToApogee>9.14375</TimeToApogee>
      <OptimalDelay>5.74375</OptimalDelay>
      <MultiDelayCount>1</MultiDelayCount>
      <VelocityAtDeplyment>18.1239</VelocityAtDeplyment>
      <AltitudeAtDeployment>361.599</AltitudeAtDeployment>
      <DelayTime>6</DelayTime>
      <EjectTime>9.4</EjectTime>
      <FinalState>2</FinalState>
      <TimeToBurnout>3.4</TimeToBurnout>
      <TimeToLanding>77.1775</TimeToLanding>
      <TimeToEject>9.4</TimeToEject>
      <MinLaunchGuideLen>1.73012</MinLaunchGuideLen>
      <MaxVertVelocity>82.713</MaxVertVelocity>
      <MaxHorzVelocity>6.6455</MaxHorzVelocity>
      <MaxVertAcceleration>64.0525</MaxVertAcceleration>
      <MaxHorzAcceleration>6.57219</MaxHorzAcceleration>
      <MaxRange>302.041</MaxRange>
      <LaunchStartVelocity>0.</LaunchStartVelocity>
      <LaunchStartRollRate>0.</LaunchStartRollRate>
      <LaunchGuideType>0</LaunchGuideType>
      <LaunchGuideLen>2438.4</LaunchGuideLen>
      <LaunchWindDirection>0</LaunchWindDirection>
      <LaunchWindSpeed>0.</LaunchWindSpeed>
      <LaunchDirection>0</LaunchDirection>
      <LaunchAngle>0.</LaunchAngle>
      <LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
      <LaunchGuideElevation>0.</LaunchGuideElevation>
      <LaunchBarometer>750.062</LaunchBarometer>
      <LaunchLatitude>37.</LaunchLatitude>
      <LaunchLongitude>0.</LaunchLongitude>
      <LaunchHumidity>50.</LaunchHumidity>
      <LaunchTemperature>15.</LaunchTemperature>
      <LaunchAltitude>213.36</LaunchAltitude>
      <LaunchLandingAltitude>213.36</LaunchLandingAltitude>
      <CompStateMask>0</CompStateMask>
      <LaunchWindPreset>4</LaunchWindPreset>
      <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
      <LaunchWindHighSpeed>6.6609</LaunchWindHighSpeed>
      <LaunchWindTurbulencePreset>99</LaunchWindTurbulencePreset>
      <LaunchWindFrequency>0.</LaunchWindFrequency>
      <LaunchWindDeltaFrequency>0.</LaunchWindDeltaFrequency>
      <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
      <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
      <LaunchCCLow>0.</LaunchCCLow>
      <LaunchCCHigh>0.1</LaunchCCHigh>
      <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
      <LaunchThermalPos>0.</LaunchThermalPos>
      <LaunchMultipleThermals>0</LaunchMultipleThermals>
      <LaunchMaxThermals>3</LaunchMaxThermals>
      <LaunchThermalDia>300.</LaunchThermalDia>
      <LaunchThermalHeight>2000.</LaunchThermalHeight>
      <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
      <LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
      <LaunchWindTableSize>0</LaunchWindTableSize>
      <LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
      <LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
      <LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
      <LaunchLossPreset>2</LaunchLossPreset>
      <LaunchLossPercent>0.99</LaunchLossPercent>
      <LaunchSiteDia>2000.</LaunchSiteDia>
      <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
      <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
      <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
      <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
      <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
      <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
      <LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
      <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
      <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
      <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
      <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
      <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
      <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
      <CNaMultiplier>1.</CNaMultiplier>
      <CdMultiplier>1.</CdMultiplier>
      <CPOffset>0.</CPOffset>
      <SaveSimAsText>0</SaveSimAsText>
      <OutputAtMaxRes>0</OutputAtMaxRes>
      <MaxSimTim>3600.</MaxSimTim>
      <MassUncertainty>0.</MassUncertainty>
      <MOIUncertainty>0.</MOIUncertainty>
      <CGUncertainty>0.</CGUncertainty>
      <CdUncertainty>0.</CdUncertainty>
      <CnaUncertainty>0.</CnaUncertainty>
      <CPUncertainty>0.</CPUncertainty>
      <FinCantUncertainty>0.</FinCantUncertainty>
      <TotImpulseUncertainty>0.</TotImpulseUncertainty>
      <PropellantUncertainty>0.</PropellantUncertainty>
      <ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
      <WindDirectionUncertainty>0.</WindDirectionUncertainty>
      <WindVelocityUncertainty>0.</WindVelocityUncertainty>
      <LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
      <LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
      <IgnitionUncertainty>0.</IgnitionUncertainty>
      <CATOUncertainty>0.</CATOUncertainty>
      <DeploymentUncertainty>0.</DeploymentUncertainty>
      <RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
      <SimulationName>[F15-6] </SimulationName>
      <VelocityAtLaunchGuideEnd>15.8715</VelocityAtLaunchGuideEnd>
      <WindStartAltitude>0.</WindStartAltitude>
      <TimeToWindShear>0.</TimeToWindShear>
      <TimeToFreeFlight>0.51625</TimeToFreeFlight>
      <TimeToMaxVelocity>3.3825</TimeToMaxVelocity>
      <TimeToMaxAcceleration>0.38625</TimeToMaxAcceleration>
      <Nsims>0</Nsims>
      <CalcResolution>1</CalcResolution>
      <SamplesPerSecond>800.</SamplesPerSecond>
      <SimulationType>4</SimulationType>
      <LocationDataServerName>Earth</LocationDataServerName>
      <LocationDataServerDisplayName>Earth</LocationDataServerDisplayName>
      <ExecutionTime>0.345</ExecutionTime>
      <RangeAtLanding>302.041</RangeAtLanding>
      <DirectionAtLanding>0.</DirectionAtLanding>
      <VelocityAtLanding>8.50157</VelocityAtLanding>
      <XVelcoityAtLanding>6.6455</XVelcoityAtLanding>
      <YVelocityAtLanding>-5.30227</YVelocityAtLanding>
      <ZVelocityAtLanding>0.</ZVelocityAtLanding>
      <StageSeparationTime>0,0,9.4,0,0</StageSeparationTime>
      <StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
      <TimeToDeployment>0,0,9.4,0,0</TimeToDeployment>
      <DeploymentType>32,32,80,32,32</DeploymentType>
      <SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
      <CalculationFlags>1</CalculationFlags>
      <Mass0>366.328</Mass0>
      <CG0>996.695</CG0>
      <LaterialMOI0>503543.</LaterialMOI0>
      <RadialMOI0>0.000160266</RadialMOI0>
      <CP0>1057.6</CP0>
      <CNA0>81.6615</CNA0>
      <SM0>1.03577</SM0>
      <GUID>{4661add3-529d-482d-b968-dac0c1699274}</GUID>
      <WeatherCocking>2</WeatherCocking>
      <RecommendedDelay>4.</RecommendedDelay>
      <RecommendedMotor>0</RecommendedMotor>
      <RecommendedMotorChecked>1</RecommendedMotorChecked>
      <TrueIndex>0</TrueIndex>
      <NinetyDegDanger>0</NinetyDegDanger>
      <VelocityGuideSafe>1</VelocityGuideSafe>
      <StaticMarginSafe>0</StaticMarginSafe>
      <VelocityDeploySafe>1</VelocityDeploySafe>
      <Booster1Staging>
        <SimulationEvent>
          <PartSerialNo>0</PartSerialNo>
          <Type>0</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
          <TestType>0,0,0</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>0</ProEvent>
        </SimulationEvent>
      </Booster1Staging>
      <Booster2Staging>
        <SimulationEvent>
          <PartSerialNo>0</PartSerialNo>
          <Type>0</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>0</HasDeployed>
          <DeployedAt_Altitude>0.</DeployedAt_Altitude>
          <DeployedAt_Velocity>0.</DeployedAt_Velocity>
          <DeployedAt_Range>0.</DeployedAt_Range>
          <DeployedAt_Time>0.</DeployedAt_Time>
          <DeviceID>-1</DeviceID>
          <TestType>0,0,0</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>0</ProEvent>
        </SimulationEvent>
      </Booster2Staging>
      <SimulationEvents>
        <SimulationEvent>
          <PartSerialNo>14</PartSerialNo>
          <Type>1</Type>
          <DeployAltitude>0.</DeployAltitude>
          <DeplyTime>0.</DeplyTime>
          <HasDeployed>1</HasDeployed>
          <DeployedAt_Altitude>361.599</DeployedAt_Altitude>
          <DeployedAt_Velocity>18.1239</DeployedAt_Velocity>
          <DeployedAt_Range>-148.374</DeployedAt_Range>
          <DeployedAt_Time>9.4</DeployedAt_Time>
          <DeviceID>128</DeviceID>
          <TestType>1,28,28</TestType>
          <TestCondition>0,0,0</TestCondition>
          <TestValueAltitude>0,0,0</TestValueAltitude>
          <TestValueDegrees>0,0,0</TestValueDegrees>
          <TestValuePressure>0,0,0</TestValuePressure>
          <TestValueMach>0,0,0</TestValueMach>
          <TestValueTime>0,0,0</TestValueTime>
          <TestValueQ>0,0,0</TestValueQ>
          <WeatherCocking>0</WeatherCocking>
          <ProEvent>1</ProEvent>
        </SimulationEvent>
      </SimulationEvents>
      <Stage1Engines>
      </Stage1Engines>
      <Stage2Engines>
      </Stage2Engines>
      <Stage3Engines>
        <EngineSet>
          <EngineCount>1</EngineCount>
          <EngineCode>F15</EngineCode>
          <IgnitionDelay>0.</IgnitionDelay>
          <EngineMfg>Estes Industries, Inc.</EngineMfg>
          <EngineOverhang>6.35</EngineOverhang>
          <CasingCG>0.</CasingCG>
          <MountSerialNo>15</MountSerialNo>
          <EjectionDelay>6.</EjectionDelay>
          <RotateXaboutY>0.</RotateXaboutY>
          <RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
        </EngineSet>
      </Stage3Engines>
      <DropItems>
      </DropItems>
    </SimulationResults>
  </SimulationResultsList>
</RockSimDocument>
